version: '3.4'
services:
    servico-01:
        image: servico-01:latest
        restart: always
        ports:
          - '9000:9000'
    servico-02:
        image: servico-02:latest
        restart: always
        ports:
          - '7000:7000'
    postgres:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./sql/insert.sql:/docker-entrypoint-initdb.d/insert.sql
      
